### ISSUE TITLE
Equivalent component for menu

### ISSUE THREAD

**Issue by damodharanj** [kor-ui/kor#30]
What is the equivalent of [menu component](https://material.angular.io/components/menu/overview) ?

The closest thing I came across was input with select, but if I reduce the width of the parent, children are also getting reduced.
Any work arounds / suggestions ?

**Comment by eduferfer** [comment]
Hello, the closest equivalent to the component you mentioned is the `kor-popover` ([see docs here](https://kor-ui.com/components/popover)).

I have created a small sample to show how it works:
https://stackblitz.com/edit/angular-ivy-9nqrut?file=src%2Fapp%2Fapp.component.html

You can use any component to trigger a popover, for example `kor-button`, `kor-menu-item` and so on.

The content of the popover is also open for you to define, so if you place menu items inside you can handle the click event as it fits your use case.

Let me know if this fits your needs or if you mean something else.
