### ISSUE TITLE
Awesome Kor

### ISSUE THREAD

**Issue by Ademking** [kor-ui/kor#40]
Thank you so much for making this awesome UI Component library.
I made this repository to lists about all kinds of interesting topics of Kor UI.
[Awesome Kor](https://github.com/Ademking/awesome-kor)

Please take a look and contribute to this repo to make it bigger and better.
If you have any useful link about Koa UI please share it with us. 
Thanks

**Comment by eduferfer** [comment]
Hi @Ademking , that is very nice of you, thanks for putting it together and we are happy to know you like Kor.

I will add a few links to the links now and also later as we publish new resources :)
