### ISSUE TITLE
Rendering issue with <kor-icon> 

### ISSUE THREAD

**Issue by GHNewbiee** [kor-ui/kor#46]
After `<kor-icon icon="favorite" size="xl"></kor-icon>`, I get (in Firefox, Waterfox) a rectangular with the following characters `E87D` (UTF-16: 0xE87D)

When `icon="train"`, I get `E570` (UTF-16: 0xE570). Web displays a solid circle/bullet.

In both cases, brave displays only a rectangular.

`<kor-icon>` is used within another component. Only very basic `css`, nothing weird!

I am not sure if browsers in my system or the system itself have been set in a wrong way or there is problem with this component.

**Comment by eduferfer** [comment]
Hi, I have 2 hypothesis to why this is happening in your project:
1. The CSS file is not loaded properly
2. The fonts are not found for some reason
3. You have reassigned the font family of `kor-icon`

Please try ensuring the css and font files are loaded and that the family is assigned correctly and update the issue if it still doesn't work.

**Comment by GHNewbiee** [comment]
1) As per doc, I have included both necessary files:
```js
import '@kor-ui/kor/components/icon';
import '@kor-ui/kor/kor-styles.css';
```
2) How can I check that? FYI, I cannot see the [Material Design Icons](https://material.io/resources/icons/?style=baseline), too!!!.
3) How can I check that?

In addition, also `url` option does not properly work.

FYI, I have not modified any file of the module. Moreover, I have removed my own css files. - *Tia*

**Comment by eduferfer** [comment]
> 1. As per doc, I have included both necessary files:
> 
> ```js
> import '@kor-ui/kor/components/icon';
> import '@kor-ui/kor/kor-styles.css';
> ```
> 
> 1. How can I check that? FYI, I cannot see the [Material Design Icons](https://material.io/resources/icons/?style=baseline), too!!!.
> 2. How can I check that?
> 
> In addition, also `url` option does not properly work.
> 
> FYI, I have not modified any file of the module. Moreover, I have removed my own css files. - _Tia_

I have created a basic sample including only sh-icon, maybe this helps: https://stackblitz.com/edit/kor-ui-angular-vkpyyc?file=src%2Fapp%2Fapp.component.ts

To check whether kor-styles.css and the font files are loaded properly, please check you console. You may have an error message saying that either `kor-styles.css` or `md-icons.woff` are not found.

The line where the local path is defined can be found here: https://github.com/kor-ui/kor/blob/develop/kor-styles.css#L45

**Comment by eduferfer** [comment]
You could also try adding the line below to your component and see if it fixes the issue. It is not a permanent solution but will show whether it is in fact a matter of the resource not being found:

```css
/* typography */
@font-face {
  font-family: 'md-icons';
  src:  local('Material Icons'), local('MaterialIcons-Regular'), url('node_modules/@kor-ui/kor/fonts/md-icons.woff2') format('woff2'), url('node_modules/@kor-ui/kor/fonts/md-icons.woff') format('woff');
}
```

**Comment by GHNewbiee** [comment]
> > 1. As per doc, I have included both necessary files:
> > 
> > ```js
> > import '@kor-ui/kor/components/icon';
> > import '@kor-ui/kor/kor-styles.css';
> > ```
> > 
> > 
> > 
> > 1. How can I check that? FYI, I cannot see the [Material Design Icons](https://material.io/resources/icons/?style=baseline), too!!!.
> > 2. How can I check that?
> > 
> > In addition, also `url` option does not properly work.
> > FYI, I have not modified any file of the module. Moreover, I have removed my own css files. - _Tia_
> 
> I have created a basic sample including only sh-icon, maybe this helps: https://stackblitz.com/edit/kor-ui-angular-vkpyyc?file=src%2Fapp%2Fapp.component.ts
> 
> To check whether kor-styles.css and the font files are loaded properly, please check you console. You may have an error message saying that either `kor-styles.css` or `md-icons.woff` are not found.
> 
> The line where the local path is defined can be found here: https://github.com/kor-ui/kor/blob/develop/kor-styles.css#L45

No error in console while running.

**Comment by GHNewbiee** [comment]
> ```css
> /* typography */
> @font-face {
>   font-family: 'md-icons';
>   src:  local('Material Icons'), local('MaterialIcons-Regular'), url('node_modules/@kor-ui/kor/fonts/md-icons.woff2') format('woff2'), url('node_modules/@kor-ui/kor/fonts/md-icons.woff') format('woff');
> }
> ```
Unfortunately, outcome is the same.

I do not really know if the root of the problem is on my side or not. So, for the time being, just keep it in back of your mind. If there is also another complaint then you can put some time to investigate it.

You can close it if you want. - *Thanks for your time!*
