### ISSUE TITLE
Support for fontawesome

### ISSUE THREAD

**Issue by gcollin** [kor-ui/kor#5]
Just a thought !
Icons can be selected amongst material design just by entering its name, that's quite convenient.
However I wonder if the same could be done with fontawesome icons, which are much more popular ?
Like https://github.com/FortAwesome/angular-fontawesome for Angular.

Right now you have to embed them in icon="url('./xxx/more.png')" which is a bit cumbersome.

**Comment by eduferfer** [comment]
Hello, taking a brief look at fontawesome, it seems quite straightforward to provide support for it too, I will investigate it further soon.
