### ISSUE TITLE
kor-ui Icons and styles not working as stated in the installation documentation 

### ISSUE THREAD

**Issue by aoloo** [kor-ui/kor#57]
I am using kor-ui for a lit-element project I have followed the docs as stated for installation. 

I added the package with this command `npm install @kor-ui/kor --save` . I then imported the components I would like to use within the project as shown in the docs. 

`
import '@kor-ui/kor/components/button';
import '@kor-ui/kor/components/Icon';
import '@kor-ui/kor/kor-styles.css';
`

But none of the styles or Icons are showing. 
![image](https://user-images.githubusercontent.com/66189547/104250778-55d93000-543c-11eb-806d-fd4da728c94b.png)

What I am doing wrong?  Any help to get me started using kor for a lit element project will be much appreciated.

**Comment by eduferfer** [comment]
Hello Allan, my first guess is that the font is not getting loaded from the css you are importing. The css itself seems to be working fine because I can see the background colors.

Is your repository public? If so could you please share a link to the file?

**Comment by aoloo** [comment]
Adding this ` <link
      rel="stylesheet"
      type="text/css"
      href="node_modules/@kor-ui/kor/kor-styles.css"
    />`  in my `index.html`   fixed my issue. Not sure why importing these components directly with styling   `import @kor-ui/kor/components/pane";
import "@kor-ui/kor/components/icon import "@kor-ui/kor/kor-styles.css`  didnt apply font-faces.

**Comment by eduferfer** [comment]
> @eduferfer adding this ` <link rel="stylesheet" type="text/css" href="node_modules/@kor-ui/kor/kor-styles.css" />` in my `index.html` fixed my issue. Not sure why importing these components directly with styling `import @kor-ui/kor/components/pane"; import "@kor-ui/kor/components/icon import "@kor-ui/kor/kor-styles.css` didnt apply font-faces.

Glad to know it worked with stylesheet import. In this case I will close this issue.
