### ISSUE TITLE
kor-input controlled component

### ISSUE THREAD

**Issue by aoloo** [kor-ui/kor#60]
```
<!-- event dispatched every time the value changes -->
<kor-input (value-changed)="myVar = $event.target.value"></kor-input>
```
I would like to have the ability to attach an `@onChange || @change` event to `kor-input` and turn it to a controlled input. The documentation states the component dispatches an event when a value is changed, but does not clarify how to access the changed value. 

```
   <kor-input
    @change="${console.log("FOO")}"
     name="EntityInput"
     label="Entity Label"
     value=${this.value}
     no-clear
     condensed>
```
It seems attaching a change event listener and making a `kor-input` into a controlled input is not possible.

**Comment by eduferfer** [comment]
Hi @aoloo I am investigating ways to fire the standard change event but it doesn't seem to be straight forward, I will update you when I know better about it.

Currently the way to get a component change and value is by listening to the -changed events and getting the event target value. For example:

```html
<!-- in LitElement -->
<kor-input
  @value-changed="${(e) => console.log(e.target.value)}"
></kor-input>

<!-- in Angular -->
<kor-input
  (value-changed)="myFunction($event.target.value)"
></kor-input>
```

**Comment by aoloo** [comment]
@eduferfer  I will use your example as a work around thanks for keeping me in the loop.

**Comment by eduferfer** [comment]
Hi @aoloo , version 1.6.0 had just been released with change events on inputs, check boxes, radio buttons and toggles, therefore I will close this issue, I hope that is fine :)
