### ISSUE TITLE
kor dropdown component

### ISSUE THREAD

**Issue by aoloo** [kor-ui/kor#61]
Would it be possible to add a dropdown component to the kor library?
![image](https://user-images.githubusercontent.com/66189547/107044654-9bb2bb00-6792-11eb-9e8c-0a41560d04d4.png)

**Comment by eduferfer** [comment]
Hi @aoloo , the dropdown component is implemented similar to the native one, please try this out:

```html
<kor-input type="select" label="Label">
  <kor-menu-item label="Item 1"></kor-menu-item>
  <kor-menu-item label="Item 2"></kor-menu-item>
  <kor-menu-item label="Item 3"></kor-menu-item>
</kor-input>
```

**Comment by aoloo** [comment]
thanks!!
