### ISSUE TITLE
React + TypeScript(TSX) issue

### ISSUE THREAD

**Issue by it1shka** [kor-ui/kor#68]
Writing litelement custom tags in React TSX causes TypeScript type errors: 

## Property 'any-litelement-name' does not exist on type 'JSX.IntrinsicElements'

The code actually compiles and works with all the type errors, but it's quite annoying

### My temporary solution was:

```typescript
declare global {
    namespace JSX {
        interface IntrinsicElements {
            'kor-page': any,
            'kor-app-bar': any,
            'kor-pane': any
            //and so on...
        }
    }
}
```

**Comment by eduferfer** [comment]
@it1shka thanks for reporting, I will investigate if there is a way to avoid manually adding the namespace interfaces. If you come across an alternative please let me know!
