### ISSUE TITLE
Need to set the default theme in host instead of html

### ISSUE THREAD

**Issue by damodharanj** [kor-ui/kor#92]
<img width="547" alt="Screenshot 2021-06-11 at 3 22 12 PM" src="https://user-images.githubusercontent.com/8286067/121668346-d58d2880-cac8-11eb-9dd1-c712aa58c715.png">

When using a kor component inside a shadow root, the default theme is not set. (Kor css is added on lazyloading inside a shadowRoot)

Can you also include 

```css
html, *[theme="light"], :host {
}
```

for the theme styles ?

**Comment by eduferfer** [comment]
Hello, yes that makes sense to me, I will include in the next patch.

**Comment by eduferfer** [comment]
> <img alt="Screenshot 2021-06-11 at 3 22 12 PM" width="547" src="https://user-images.githubusercontent.com/8286067/121668346-d58d2880-cac8-11eb-9dd1-c712aa58c715.png">
> 
> When using a kor component inside a shadow root, the default theme is not set. (Kor css is added on lazyloading inside a shadowRoot)
> 
> Can you also include
> 
> ```css
> html, *[theme="light"], :host {
> }
> ```
> 
> for the theme styles ?

Hi, this fix is now published with patch `1.8.2`, thanks for the suggestion.

**Comment by avizcaino** [comment]
Hi! Shouldn't also be included for the dark theme?
